### PR TITLE
Fix service listener becoming zombie

### LINKED ISSUE #4: onNotificationReceived stop working after a while
I put the library in my app, at first it worked properly. But after a moment(about 20 mins), onNotificationReceived no longer be called. I suspect the service was recycled by OS, after some google, I found same issues [here](https://gist.github.com/xinghui/b2ddd8cffe55c4b62f5d8846d5545bf9).
As the writer said, NLS became a zombie service, which caused onNotificationReceived losing its function. I also test it with adb command:`adb shell dumpsys notification`, found the app disappear from the "Live Notification Listeners" section.
I'm a newbie in native android, do you have any suggestions?

### PR DESCRIPTION
**Pull request by leandrosimoes**
# Changes

* Add Headless JS service to avoid the notification listener to be killed by Android
* Add Boot Up Receiver to restart the service in case the user reboots the device as soon the OS restart
* Some Eslint and Prettier configuration improvements

# Breaking changes

* Removed the method `onNotificationReceived` because now the handle must be made using the `AppRegistry`. (See the documentation [here](https://github.com/leandrosimoes/react-native-android-notification-listener))

Closes #4

### CODE REVIEW

File: sample/App.js [hunk 1]
```diff
@@ -1,96 +1,66 @@
...
-    RNAndroidNotificationListener.getPermissionStatus().then(status => {
-      setHasPermission(status !== 'denied');
-    });
+    useEffect(() => {
+        AppState.addEventListener('change', handleAppStateChange)
 
-    RNAndroidNotificationListener.onNotificationReceived(
-      handleNotificationReceived,
-    );
+        AppRegistry.registerHeadlessTask(
```
Comment (jehartzog) [inline sample/App.js:32]: I don't think this is the right place to register this task, even though the effect is correctly set up to only be run once.

This should be in `sample/index.js` and use a module import as needed to register the correct function.

I guess this conflicts with the simple example though, which just uses React state without needing any sort of external store? If you can't think of an easy way to do this without refactoring the whole sample, I'd just add a comment about this right here.

From Docs: [https://reactnative.dev/docs/appregistry]
>AppRegistry should be required early in the require sequence to make sure the JS execution environment is setup before other modules are required.

Comment (jehartzog) [reply sample/App.js:32]: Actually now that I think about it, it's a strong possibility this will not work at all.

When RN Android boots up the JS looking for a headless task to execute, I'm not 100% sure it will actually mount a UI for the normal RN bridge to interact with. I suspect it won't, which means your React UI won't be mounted, and this effect will never be triggered. Since the task is never registered, it will likely fail with a logged error.

Comment (leandrosimoes) [reply sample/App.js:32]: Nice observation @jehartzog ... I'll change the implementation to `sample/index` and do some tests using AsyncStorage to store the notification payloads to see how the service will respond, even after restarting the device and closing the application. The [BootUpReceiver](https://github.com/leandrosimoes/react-native-android-notification-listener/pull/6/files#diff-22c310e837f24cbedd8672e9c6417b8f091cd024012686212f629a5733229204) should start the service automatically as soon as the device restart.

I'll do some tests and let you know.

Comment (leandrosimoes) [reply sample/App.js:32]: @jehartzog ... I did the changes, put the `AppRegistry` and the handle function in the `sample/index`. Inside the handle function, I put a code to store the notification in the AsyncStorage. After that, I install the release version of the sample application on my device and restarted it. As soon as my device finished to boot up, and without open the sample application, I sent a new notification to another app on my device and received it. Then I open the sample application and the notification was there in the AsyncStorage! So I think that this way will work just fine.

Any other thoughts to be considered here?

Comment (jehartzog) [reply sample/App.js:32]: Nope, `AsyncStorage` is the perfect solution to show how this needs to work. RN devs will understand it easily, and those using some sort of external data store/API to actually use the functionality will easily be able to modify it to work for their use case. The updated example helps show how the `headlessJS` portion is actually completely separate from the `React` UI, and so you need some external data linkage (`AsyncStorage`  or API based) to make it functional.

I didn't actually see the updates to this PR since you haven't pushed them yet, but the idea sounds good.

Comment (leandrosimoes) [reply sample/App.js]: Awesome @jehartzog ... Sorry about not having pushed yet, I just wanted to confirm with you before pushing but now is all pushed. Take a look and let me know if everything looks fine, pls!

Comment (jehartzog) [reply sample/App.js]: @leandrosimoes Looks solid.

Comment (leandrosimoes) [reply sample/App.js]: Awesome @jehartzog, thanks a lot for the help. I'll merge this branch and release a version in a few minutes.
